openapi: 3.0.3

info:
  title: Bingo Tournament API
  description: API used to schedule races and query race results
  version: 0.0.2

servers:
  - url: http://localhost:8080/api
    description: Local development environment

paths:
  /health:
    get:
      summary: Health Endpoint
      description: Returns a success immediately
      operationId: getHealth
      responses:
        204:
          description: The application is running
  /user:
    get:
      summary: Get logged in user
      description: Returns the details of the current user, if logged in.
      operationId: getUser
      responses:
        200:
          description: The user details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        403:
          description: No user logged in

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar:
          type: string
          format: uri
        twitchChannel:
          type: string
          format: uri
      required:
        - id
        - name
