openapi: 3.0.3

info:
  title: Bingo Tournament API
  description: API used to schedule races and query race results
  version: 0.0.4

servers:
  - url: http://localhost:8080/api
    description: Local development environment

paths:
  /health:
    get:
      summary: Health Endpoint
      description: Returns a success immediately
      operationId: getHealth
      responses:
        204:
          description: The application is running
  /user:
    get:
      summary: Get logged in user
      description: Returns the details of the current user, if logged in.
      operationId: getUser
      responses:
        200:
          description: The user details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: No user logged in
  /entrants:
    get:
      summary: Get entrant list
      description: Returns a list of all users with the ENTRANT role. Only administrators can retrieve this information.
      operationId: getEntrants
      responses:
        200:
          description: The entrant list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        401:
          description: No user logged in
        403:
          description: Insufficient rights
  /signup:
    post:
      summary: Sign up for the tournament
      description: Signs the current user up for the tournament
      operationId: signUp
      responses:
        204:
          description: User is signed up
        401:
          description: No user logged in
    delete:
      summary: Withdraw from the tournament
      description: Withdraws the current user from the tournament
      operationId: withdraw
      responses:
        204:
          description: User is withdrawn
        401:
          description: No user logged in

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar:
          type: string
          format: uri
        twitchChannel:
          type: string
          format: uri
      required:
        - id
        - name
