version: "3.9"
services:
  db:
    image: postgres:14-alpine
    container_name: bingo-tournament-dev-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./dev_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
