bingo:
  backend:
    base-url: "{baseUrl}"
  frontend:
    base-url: http://localhost:3000
  oauth:
    racetime:
      base-url: "${gg.racetime.api.base-url}"
  users:
    admins:
      - d17DexWEKg3ak64R
      - pRbOXG3ykOWZVKq1

gg:
  racetime:
    api:
      base-url: http://localhost:8000

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    converters:
      preferred-json-mapper: gson

  security:
    oauth2:
      client:
        provider:
          racetime:
            authorizationUri: "${bingo.oauth.racetime.base-url}/o/authorize"
            tokenUri: "${bingo.oauth.racetime.base-url}/o/token"
            userInfoUri: "${bingo.oauth.racetime.base-url}/o/userinfo"
        registration:
          racetime:
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - read
            redirectUri: "${bingo.backend.base-url}/login/oauth2/code/racetime"
            clientName: OoT Bingo Tournament

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      days: 10
