bingo:
  backend:
    base-url: https://bingo-tournament.scaramangado.de
  frontend:
    base-url: https://bingo-tournament.scaramangado.de

gg:
  racetime:
    api:
      base-url: https://racetime.gg

spring:
  datasource:
    url: jdbc:postgresql://bingo-tournament-db:5432/postgres

logging:
  file:
    name: tournament.log
    max-history: 15
  pattern:
    console:
  logback:
    rollingpolicy:
      file-name-pattern: tournament_%d{yyyy-MM-dd}_%i.log
