bingo:
  backend:
    base-url: https://bingo-tournament.scaramangado.de
  frontend:
    base-url: https://xwmtp.github.io/bingo2022

gg:
  racetime:
    api:
      base-url: https://racetime.gg

spring:
  datasource:
    url: jdbc:postgresql://bingo-tournament-db:5432/postgres

logging:
  file:
    name: tournament.log
    max-history: 15
  pattern:
    console:
