version: "3.9"
services:
  backend:
    image: ghcr.io/xwmtp/bingo-tournament/bingo-tournament:latest
    container_name: bingo-tournament
    restart: unless-stopped
    volumes:
      - "./volumes/bingo-tournament:/etc/bingo-tournament"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - nginx
      - tournament
    depends_on:
      - tournament-db
  frontend:
    image: ghcr.io/xwmtp/bingo2023/bingo-tournament-fe:latest
    container_name: bingo-tournament-fe
    restart: unless-stopped
    ports:
      - "3210:80"
    networks:
      - nginx
      - tournament
    depends_on:
      - backend
  tournament-db:
    image: postgres:14-alpine
    container_name: bingo-tournament-db
    restart: unless-stopped
    volumes:
      - "./volumes/db_data:/var/lib/postgresql/data"
      - "./volumes/db_secrets:/oot/db_secrets"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD_FILE: "/oot/db_secrets/postgres_pwd"
    networks:
      - tournament

networks:
  nginx:
    name: nginx
    external: true
  tournament:
