name: Build and publish NPM Package

on:
  push:
    branches:
      - main
    paths:
      - api/**.yaml
      - .github/workflows/npm.yaml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@xwmtp"
      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: OpenAPI Generation
        run: ./gradlew openApiNpm
      - name: Install Packages
        working-directory: ./npm
        run: npm install
      - name: Build
        working-directory: ./npm
        run: npm run prepare
      - name: Publish
        working-directory: ./npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
